from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List

from .artifact_store import LOCAL_STATE_DIR, write_json
from .chunker import chunk_documents
from .demo_docs import build_demo_documents
from .document_store import load_local_normalized_documents
from .graph_export import build_evidence_manifest, export_graph


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def build_preloaded_claims() -> List[Dict[str, Any]]:
    created_at = _now()
    return [
        {
            "claim_id": "claim_ema_gcp_qa_protocol_adherence",
            "claim_text": "Protocol adherence is fundamental to clinical study conduct.",
            "normalized_subject": "regulation.protocol_adherence",
            "predicate": "states",
            "normalized_object": "protocol adherence is fundamental",
            "claim_type": "recommendation",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": None,
            "evidence_ids": ["chunk_ema_gcp_qa_c8843dc9de11"],
            "source_ids": ["ema_gcp_qa"],
            "citation_spans": [{"source_id": "ema_gcp_qa", "locator": "Protocol adherence", "quoted_text": "Adherence to the protocol is a fundamental part of the conduct of a clinical study."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": [],
            "retrieval_keywords": [],
            "retrieval_summary": "Protocol adherence is fundamental to clinical study conduct.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_fda_ind_protocol_amendments_protocol_amendment_requirement",
            "claim_text": "Protocol changes should be submitted as protocol amendments before implementation or as required by the process.",
            "normalized_subject": "regulation.protocol_amendment_requirement",
            "predicate": "requires",
            "normalized_object": "protocol amendment submission for protocol changes",
            "claim_type": "requirement",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": None,
            "evidence_ids": ["chunk_fda_ind_protocol_amendments_45389ba61c83"],
            "source_ids": ["fda_ind_protocol_amendments"],
            "citation_spans": [{"source_id": "fda_ind_protocol_amendments", "locator": "Timing", "quoted_text": "Sponsors are expected to submit protocol amendments for new protocols or changes to existing protocols before implementation of the respective changes."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": [],
            "retrieval_keywords": [],
            "retrieval_summary": "Protocol changes should be submitted as protocol amendments before implementation or as required by the process.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_protocol_v1_dose_50mg",
            "claim_text": "The protocol dose is 50 mg once daily.",
            "normalized_subject": "protocol.current_dose",
            "predicate": "equals",
            "normalized_object": "50 mg once daily",
            "claim_type": "factual",
            "claim_status": "superseded",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": "claim_protocol_amendment_v2_dose_75mg",
            "evidence_ids": ["chunk_protocol_v1_70170f9cf6ee"],
            "source_ids": ["protocol_v1"],
            "citation_spans": [{"source_id": "protocol_v1", "locator": "Section 6.2 Dosing and Administration", "quoted_text": "Subjects will receive 50 mg once daily."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": [],
            "retrieval_keywords": [],
            "retrieval_summary": "The protocol dose is 50 mg once daily.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_protocol_v1_visit_14days",
            "claim_text": "Visits occur every 14 days.",
            "normalized_subject": "protocol.visit_interval",
            "predicate": "equals",
            "normalized_object": "14 days",
            "claim_type": "factual",
            "claim_status": "superseded",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": "claim_protocol_amendment_v2_visit_21days",
            "evidence_ids": ["chunk_protocol_v1_227e70fb6f12"],
            "source_ids": ["protocol_v1"],
            "citation_spans": [{"source_id": "protocol_v1", "locator": "Section 7.1 Visit Schedule", "quoted_text": "Subjects will attend visits every 14 days."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": [],
            "retrieval_keywords": [],
            "retrieval_summary": "Visits occur every 14 days.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_protocol_amendment_v2_dose_change_50_to_75",
            "claim_text": "The protocol dose changed from 50 mg once daily to 75 mg once daily.",
            "normalized_subject": "protocol.current_dose",
            "predicate": "changes_to",
            "normalized_object": "75 mg once daily",
            "claim_type": "change_event",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": None,
            "evidence_ids": ["chunk_protocol_amendment_v2_484d06642acb"],
            "source_ids": ["protocol_amendment_v2"],
            "citation_spans": [{"source_id": "protocol_amendment_v2", "locator": "Section 6.2 Dosing and Administration", "quoted_text": "Dose will be increased from 50 mg to 75 mg once daily."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": [],
            "retrieval_keywords": [],
            "retrieval_summary": "The protocol dose changed from 50 mg once daily to 75 mg once daily.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_protocol_amendment_v2_dose_75mg",
            "claim_text": "The current protocol dose is 75 mg once daily.",
            "normalized_subject": "protocol.current_dose",
            "predicate": "equals",
            "normalized_object": "75 mg once daily",
            "claim_type": "factual",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": ["claim_protocol_v1_dose_50mg"],
            "superseded_by_claim_id": None,
            "evidence_ids": ["chunk_protocol_amendment_v2_484d06642acb"],
            "source_ids": ["protocol_amendment_v2"],
            "citation_spans": [{"source_id": "protocol_amendment_v2", "locator": "Section 6.2 Dosing and Administration", "quoted_text": "Dose will be increased from 50 mg to 75 mg once daily."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": [],
            "retrieval_keywords": [],
            "retrieval_summary": "The current protocol dose is 75 mg once daily.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_protocol_amendment_v2_visit_21days",
            "claim_text": "Visits occur every 21 days.",
            "normalized_subject": "protocol.visit_interval",
            "predicate": "equals",
            "normalized_object": "21 days",
            "claim_type": "factual",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": ["claim_protocol_v1_visit_14days"],
            "superseded_by_claim_id": None,
            "evidence_ids": ["chunk_protocol_amendment_v2_e58749f3a122", "chunk_visit_schedule_table_9ce7dc927bcd"],
            "source_ids": ["protocol_amendment_v2", "visit_schedule_table"],
            "citation_spans": [
                {"source_id": "protocol_amendment_v2", "locator": "Section 7.1 Visit Schedule", "quoted_text": "Subjects will attend visits every 21 days."},
                {"source_id": "visit_schedule_table", "locator": "Visit Schedule Changes", "quoted_text": "v1 shows visits every 14 days. Amendment v2 changes visits to every 21 days."},
            ],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": [],
            "retrieval_keywords": [],
            "retrieval_summary": "Visits occur every 21 days.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_sop_dose_change_citation_dose_change_citation",
            "claim_text": "Dose changes must be cited to the source amendment.",
            "normalized_subject": "sop.dose_change_citation_requirement",
            "predicate": "requires",
            "normalized_object": "citation to source amendment",
            "claim_type": "requirement",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": None,
            "evidence_ids": ["chunk_sop_dose_change_citation_c845e363284c"],
            "source_ids": ["sop_dose_change_citation"],
            "citation_spans": [{"source_id": "sop_dose_change_citation", "locator": "Dose Change Citation Policy", "quoted_text": "Any dose change in a protocol or protocol amendment must be cited to the source amendment in the final drafting output."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": [],
            "retrieval_keywords": [],
            "retrieval_summary": "Dose changes must be cited to the source amendment.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_visit_schedule_table_visit_change_14_to_21",
            "claim_text": "The protocol visit interval changed from 14 days to 21 days.",
            "normalized_subject": "protocol.visit_interval",
            "predicate": "changes_to",
            "normalized_object": "21 days",
            "claim_type": "change_event",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": None,
            "evidence_ids": ["chunk_visit_schedule_table_9ce7dc927bcd"],
            "source_ids": ["visit_schedule_table"],
            "citation_spans": [{"source_id": "visit_schedule_table", "locator": "Visit Schedule Changes", "quoted_text": "v1 shows visits every 14 days. Amendment v2 changes visits to every 21 days."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": [],
            "retrieval_keywords": [],
            "retrieval_summary": "The protocol visit interval changed from 14 days to 21 days.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_protocol_v1_exclusion_fluvoxamine",
            "claim_text": "Subjects currently receiving fluvoxamine are excluded.",
            "normalized_subject": "protocol.exclusion_criteria",
            "predicate": "equals",
            "normalized_object": "fluvoxamine",
            "claim_type": "factual",
            "claim_status": "superseded",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": "claim_protocol_amendment_v2_exclusion_fluvoxamine_ciprofloxacin",
            "evidence_ids": ["chunk_protocol_v1_070bdcd08ff3"],
            "source_ids": ["protocol_v1"],
            "citation_spans": [{"source_id": "protocol_v1", "locator": "Section 5.2 Eligibility Criteria", "quoted_text": "Subjects currently receiving fluvoxamine are excluded."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": [],
            "retrieval_keywords": [],
            "retrieval_summary": "Subjects currently receiving fluvoxamine are excluded.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_protocol_amendment_v2_exclusion_change_fluvoxamine_ciprofloxacin",
            "claim_text": "The exclusion criteria changed from fluvoxamine to fluvoxamine, ciprofloxacin.",
            "normalized_subject": "protocol.exclusion_criteria",
            "predicate": "changes_to",
            "normalized_object": "fluvoxamine, ciprofloxacin",
            "claim_type": "change_event",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": None,
            "evidence_ids": ["chunk_protocol_amendment_v2_2473ca817ec9"],
            "source_ids": ["protocol_amendment_v2"],
            "citation_spans": [{"source_id": "protocol_amendment_v2", "locator": "Section 5.2 Eligibility Criteria", "quoted_text": "Exclusion criteria updated: subjects currently receiving fluvoxamine or ciprofloxacin are excluded."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": [],
            "retrieval_keywords": [],
            "retrieval_summary": "The exclusion criteria changed from fluvoxamine to fluvoxamine, ciprofloxacin.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_protocol_amendment_v2_exclusion_fluvoxamine_ciprofloxacin",
            "claim_text": "The current exclusion criteria are fluvoxamine, ciprofloxacin.",
            "normalized_subject": "protocol.exclusion_criteria",
            "predicate": "equals",
            "normalized_object": "fluvoxamine, ciprofloxacin",
            "claim_type": "factual",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": ["claim_protocol_v1_exclusion_fluvoxamine"],
            "superseded_by_claim_id": None,
            "evidence_ids": ["chunk_protocol_amendment_v2_2473ca817ec9"],
            "source_ids": ["protocol_amendment_v2"],
            "citation_spans": [{"source_id": "protocol_amendment_v2", "locator": "Section 5.2 Eligibility Criteria", "quoted_text": "Exclusion criteria updated: subjects currently receiving fluvoxamine or ciprofloxacin are excluded."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": [],
            "retrieval_keywords": [],
            "retrieval_summary": "The current exclusion criteria are fluvoxamine, ciprofloxacin.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_fda_ind_protocol_amendments_dose_increase_requires_amendment",
            "claim_text": "Any increase in drug dosage beyond the current protocol requires a protocol amendment.",
            "normalized_subject": "regulation.amendment_required_for_dose_increase",
            "predicate": "requires",
            "normalized_object": "protocol amendment required",
            "claim_type": "requirement",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": None,
            "evidence_ids": [],
            "source_ids": ["fda_ind_protocol_amendments"],
            "citation_spans": [{"source_id": "fda_ind_protocol_amendments", "locator": "Example protocol changes", "quoted_text": "Any increase in drug dosage or duration of exposure beyond the current protocol may require an amendment."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": ["amendment", "dose"],
            "retrieval_keywords": [],
            "retrieval_summary": "Dose increases beyond the current protocol require a protocol amendment.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_fda_ind_protocol_amendments_design_change_requires_amendment",
            "claim_text": "Any significant protocol design change requires a protocol amendment.",
            "normalized_subject": "regulation.amendment_required_for_design_change",
            "predicate": "requires",
            "normalized_object": "protocol amendment required",
            "claim_type": "requirement",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": None,
            "evidence_ids": [],
            "source_ids": ["fda_ind_protocol_amendments"],
            "citation_spans": [{"source_id": "fda_ind_protocol_amendments", "locator": "Example protocol changes", "quoted_text": "Any significant change in the design of a protocol requires amendment submission."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": ["amendment", "design"],
            "retrieval_keywords": [],
            "retrieval_summary": "Significant protocol design changes require a protocol amendment.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_fda_ind_protocol_amendments_safety_monitoring_change_requires_amendment",
            "claim_text": "Adding or removing monitoring procedures related to side effects requires a protocol amendment.",
            "normalized_subject": "regulation.amendment_required_for_safety_monitoring_change",
            "predicate": "requires",
            "normalized_object": "protocol amendment required",
            "claim_type": "requirement",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": None,
            "evidence_ids": [],
            "source_ids": ["fda_ind_protocol_amendments"],
            "citation_spans": [{"source_id": "fda_ind_protocol_amendments", "locator": "Example protocol changes", "quoted_text": "Addition or elimination of safety monitoring tests may require an amendment."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": ["amendment", "safety"],
            "retrieval_keywords": [],
            "retrieval_summary": "Safety monitoring changes require a protocol amendment.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_fda_ind_protocol_amendments_immediate_hazard_exception",
            "claim_text": "A protocol change to eliminate an immediate hazard may be implemented immediately if FDA and the IRB are notified afterward.",
            "normalized_subject": "regulation.immediate_hazard_exception",
            "predicate": "permits",
            "normalized_object": "implement immediately then notify FDA and IRB",
            "claim_type": "recommendation",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": None,
            "evidence_ids": [],
            "source_ids": ["fda_ind_protocol_amendments"],
            "citation_spans": [{"source_id": "fda_ind_protocol_amendments", "locator": "Immediate hazard note", "quoted_text": "A change intended to eliminate an apparent immediate hazard may be implemented immediately with subsequent notification."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": ["amendment", "hazard"],
            "retrieval_keywords": [],
            "retrieval_summary": "Immediate-hazard changes may be implemented immediately with subsequent notification.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_ema_gcp_qa_source_data_identification",
            "claim_text": "The protocol should identify any data recorded directly into CRFs that are considered source data.",
            "normalized_subject": "regulation.source_data_identification_requirement",
            "predicate": "requires",
            "normalized_object": "identify source data recorded directly into CRFs",
            "claim_type": "requirement",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": None,
            "evidence_ids": [],
            "source_ids": ["ema_gcp_qa"],
            "citation_spans": [{"source_id": "ema_gcp_qa", "locator": "Source data requirements", "quoted_text": "The protocol should identify data recorded directly into the CRFs that are considered source data."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": ["source data", "gcp"],
            "retrieval_keywords": [],
            "retrieval_summary": "The protocol should identify CRF-recorded source data.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_ema_gcp_qa_eligibility_documentation",
            "claim_text": "Adherence to individual inclusion and exclusion criteria should be documented in source data.",
            "normalized_subject": "regulation.eligibility_documentation_requirement",
            "predicate": "requires",
            "normalized_object": "document individual eligibility criteria in source data",
            "claim_type": "requirement",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": None,
            "evidence_ids": [],
            "source_ids": ["ema_gcp_qa"],
            "citation_spans": [{"source_id": "ema_gcp_qa", "locator": "Eligibility documentation", "quoted_text": "Adherence to all individual inclusion and exclusion criteria are documented in the source data."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": ["eligibility", "gcp"],
            "retrieval_keywords": [],
            "retrieval_summary": "Individual eligibility criteria should be documented in source data.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_cdisc_home_prm_scope",
            "claim_text": "CDISC Protocol Representation Model focuses on study design, eligibility criteria, and registry requirements.",
            "normalized_subject": "cdisc.protocol_representation_scope",
            "predicate": "states",
            "normalized_object": "study design, eligibility criteria, and registry requirements",
            "claim_type": "recommendation",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": None,
            "evidence_ids": [],
            "source_ids": ["cdisc_home"],
            "citation_spans": [{"source_id": "cdisc_home", "locator": "Protocol Representation Model", "quoted_text": "PRM focuses on study design, eligibility criteria, and registry requirements."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": ["cdisc", "protocol"],
            "retrieval_keywords": [],
            "retrieval_summary": "CDISC PRM covers study design, eligibility criteria, and registry requirements.",
            "created_at": created_at,
        },
        {
            "claim_id": "claim_fda_clinical_protocols_phase1_safety_detail",
            "claim_text": "Phase 1 protocols should specify safety-critical elements such as toxicity monitoring, stopping rules, and dose adjustment rules.",
            "normalized_subject": "regulation.phase1_protocol_safety_detail_requirement",
            "predicate": "requires",
            "normalized_object": "toxicity monitoring, stopping rules, and dose adjustment rules",
            "claim_type": "requirement",
            "claim_status": "active",
            "effective_start": created_at,
            "effective_end": None,
            "supersedes_claim_ids": [],
            "superseded_by_claim_id": None,
            "evidence_ids": [],
            "source_ids": ["fda_clinical_protocols"],
            "citation_spans": [{"source_id": "fda_clinical_protocols", "locator": "Phase 1 trial expectations", "quoted_text": "Early developmental protocols should specify all safety-critical elements, including toxicity monitoring and stopping or dose-adjustment rules."}],
            "extraction_method": "preloaded_local_demo",
            "extraction_confidence": 0.8,
            "reviewer_decision": None,
            "reviewer_notes": None,
            "entity_ids": [],
            "relation_ids": [],
            "topic_labels": ["phase 1", "safety"],
            "retrieval_keywords": [],
            "retrieval_summary": "Phase 1 protocols should specify safety-critical monitoring and dose-adjustment rules.",
            "created_at": created_at,
        },
    ]


def ensure_local_demo_state(reset: bool = False) -> None:
    claims_path = LOCAL_STATE_DIR / "claims" / "claim_ledger.json"
    if claims_path.exists() and not reset:
        return

    docs = load_local_normalized_documents() + build_demo_documents()
    chunks = chunk_documents(docs)
    claims = build_preloaded_claims()
    graph = export_graph(claims)
    evidence_manifest = build_evidence_manifest(chunks)

    write_json("normalized/demo_documents.json", build_demo_documents())
    write_json("chunks/all_chunks.json", chunks)
    write_json("chunks/evidence_manifest.json", evidence_manifest)
    write_json("claims/claim_ledger.json", claims)
    write_json("claims/approval_events.json", [])
    write_json(
        "claims/review_manifest.json",
        {
            "last_reviewed_at": None,
            "approved_claim_id": None,
            "reviewer": None,
            "ledger_blob": "claims/claim_ledger.json",
            "approval_events_blob": "claims/approval_events.json",
        },
    )
    write_json("graph/nodes.json", graph["nodes"])
    write_json("graph/edges.json", graph["edges"])
    write_json(
        "graph/graph_manifest.json",
        {
            "nodes_total": len(graph["nodes"]),
            "edges_total": len(graph["edges"]),
            "claims_total": len(claims),
            "chunks_total": len(chunks),
            "outputs": {
                "nodes": "graph/nodes.json",
                "edges": "graph/edges.json",
                "evidence_manifest": "chunks/evidence_manifest.json",
            },
        },
    )
